### ISSUE TITLE
支持 uniCloud 吗？

### ISSUE THREAD

**Issue by topazur** [sunpm/vitesse-uniapp-vue3#29]

**Comment by sunpm** [comment]
很抱歉，uniCloud 没使用过，您可以帮我试试吗🙏

**Comment by topazur** [comment]
主要是 hb 起了一个本地服务，我不知道这个 server 开源了没有。每次上传后再使用体验很差

**Comment by sunpm** [comment]
uniapp 文档说：
> 如果你习惯其他ide，开发uni-app低效也无所谓，那也可以用其他ide。但注意至少运行调试app和uniCloud时，还得把HBuilderX开着，就像开着微信小程序工具调试那样。
>
> 其他ide没有uni-app的app和uniCloud的运行、调试工具。这些工具在HBuilderX里。如开发app和uniCloud，必须使用HBuilderX。

https://zh.uniapp.dcloud.io/quickstart-cli.htm

应该可以用吧。。。对。。。应该。。。
